apiVersion: v1
kind: Namespace
metadata:
  name: kpack
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: builds.build.pivotal.io
spec:
  group: build.pivotal.io
  version: v1alpha1
  names:
    kind: Build
    singular: build
    plural: builds
    shortNames:
    - cnbbuild
    - cnbbuilds
    - bld
    categories:
    - kpack
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: Image
    type: string
    JSONPath: .status.latestImage
  - name: Succeeded
    type: string
    JSONPath: .status.conditions[?(@.type=="Succeeded")].status
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: builders.build.pivotal.io
spec:
  group: build.pivotal.io
  version: v1alpha1
  names:
    kind: Builder
    singular: builder
    plural: builders
    shortNames:
    - cnbbuilder
    - cnbbuilders
    - bldr
    categories:
    - kpack
  scope: Namespaced
  subresources:
    status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterbuilders.build.pivotal.io
spec:
  group: build.pivotal.io
  version: v1alpha1
  names:
    kind: ClusterBuilder
    singular: clusterbuilder
    plural: clusterbuilders
    shortNames:
    - clstbldr
    categories:
    - kpack
  scope: Cluster
  subresources:
    status: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kpack-admin
rules:
- apiGroups:
  - build.pivotal.io
  resources:
  - builds
  - builds/status
  - images
  - images/status
  - builders
  - builders/status
  - clusterbuilders
  - clusterbuilders/status
  - sourceresolvers
  - sourceresolvers/status
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - pods
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kpack-controller-admin
subjects:
- kind: ServiceAccount
  name: controller
  namespace: kpack
roleRef:
  kind: ClusterRole
  name: kpack-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpack-controller
  namespace: kpack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpack-controller
  template:
    metadata:
      labels:
        app: kpack-controller
        version: dev
    spec:
      serviceAccountName: controller
      containers:
      - name: controller
        image: kpack/controller@sha256:386c23ff41b9986daa2dbe8069614bc79661e1244b7699d2b78a447403682e37
        env:
        - name: BUILD_INIT_IMAGE
          value: kpack/build-init@sha256:809584bd8460a458fb5bee504dad4dd33e039961061436042915ac4e118f9981
        - name: NOP_IMAGE
          value: gcr.io/pivotal-knative/github.com/knative/build/cmd/nop@sha256:dc7e5e790001c71c2cfb175854dd36e65e0b71c58294b331a519be95bdec4ef4
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: images.build.pivotal.io
spec:
  group: build.pivotal.io
  version: v1alpha1
  names:
    kind: Image
    singular: image
    plural: images
    shortNames:
    - cnbimage
    - cnbimages
    categories:
    - kpack
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: LatestImage
    type: string
    JSONPath: .status.latestImage
  - name: Ready
    type: string
    JSONPath: .status.conditions[?(@.type=="Ready")].status
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  namespace: kpack
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sourceresolvers.build.pivotal.io
spec:
  group: build.pivotal.io
  version: v1alpha1
  names:
    kind: SourceResolver
    singular: sourceresolver
    plural: sourceresolvers
    categories:
    - kpack
  scope: Namespaced
  subresources:
    status: {}
