/*
 * Copyright 2019 The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/pivotal/kpack/pkg/apis/experimental/v1alpha1"
	scheme "github.com/pivotal/kpack/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CustomBuilderListsGetter has a method to return a CustomBuilderListInterface.
// A group's client should implement this interface.
type CustomBuilderListsGetter interface {
	CustomBuilderLists(namespace string) CustomBuilderListInterface
}

// CustomBuilderListInterface has methods to work with CustomBuilderList resources.
type CustomBuilderListInterface interface {
	Create(*v1alpha1.CustomBuilderList) (*v1alpha1.CustomBuilderList, error)
	Update(*v1alpha1.CustomBuilderList) (*v1alpha1.CustomBuilderList, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.CustomBuilderList, error)
	List(opts v1.ListOptions) (*v1alpha1.CustomBuilderListList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CustomBuilderList, err error)
	CustomBuilderListExpansion
}

// customBuilderLists implements CustomBuilderListInterface
type customBuilderLists struct {
	client rest.Interface
	ns     string
}

// newCustomBuilderLists returns a CustomBuilderLists
func newCustomBuilderLists(c *ExperimentalV1alpha1Client, namespace string) *customBuilderLists {
	return &customBuilderLists{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the customBuilderList, and returns the corresponding customBuilderList object, and an error if there is any.
func (c *customBuilderLists) Get(name string, options v1.GetOptions) (result *v1alpha1.CustomBuilderList, err error) {
	result = &v1alpha1.CustomBuilderList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("custombuilderlists").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CustomBuilderLists that match those selectors.
func (c *customBuilderLists) List(opts v1.ListOptions) (result *v1alpha1.CustomBuilderListList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CustomBuilderListList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("custombuilderlists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested customBuilderLists.
func (c *customBuilderLists) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("custombuilderlists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a customBuilderList and creates it.  Returns the server's representation of the customBuilderList, and an error, if there is any.
func (c *customBuilderLists) Create(customBuilderList *v1alpha1.CustomBuilderList) (result *v1alpha1.CustomBuilderList, err error) {
	result = &v1alpha1.CustomBuilderList{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("custombuilderlists").
		Body(customBuilderList).
		Do().
		Into(result)
	return
}

// Update takes the representation of a customBuilderList and updates it. Returns the server's representation of the customBuilderList, and an error, if there is any.
func (c *customBuilderLists) Update(customBuilderList *v1alpha1.CustomBuilderList) (result *v1alpha1.CustomBuilderList, err error) {
	result = &v1alpha1.CustomBuilderList{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("custombuilderlists").
		Name(customBuilderList.Name).
		Body(customBuilderList).
		Do().
		Into(result)
	return
}

// Delete takes name of the customBuilderList and deletes it. Returns an error if one occurs.
func (c *customBuilderLists) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("custombuilderlists").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *customBuilderLists) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("custombuilderlists").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched customBuilderList.
func (c *customBuilderLists) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CustomBuilderList, err error) {
	result = &v1alpha1.CustomBuilderList{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("custombuilderlists").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
